services:
  frontend:
    build: 
      dockerfile: dockerfiles/frontend.dockerfile
    ports:
      - 80:80
    expose:
      - "8080"
      - "80"
    # volumes:
    #   - ./frontend/:/app      
    restart: always
  api:
    build:
      dockerfile: dockerfiles/api.dockerfile
    expose:
      - "8000"
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      # - ./ :/app
      - database_volume:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  worker:
    container_name: api-celery-worker
    build:
      dockerfile: dockerfiles/api.dockerfile
    command: ./celery/celery-entrypoint.sh
    volumes:
      - database_volume:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis
    restart: always

  redis:
    image: redis

volumes:
  database_volume: