services:
  api:
    build:
      dockerfile: dockerfiles/api.dockerfile
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    container_name: api-celery-worker
    build:
      dockerfile: dockerfiles/api.dockerfile
    command: ./celery/celery-entrypoint.sh
    volumes:
      - ./:/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - api
      - redis

  redis:
    image: redis