services:
  frontend:
    build: 
      dockerfile: dockerfiles/frontend.dockerfile
    ports:
      - 80:80
    expose:
      - "8080"
      - "80"
    # volumes:
    #   - ./frontend/:/app      
    restart: always
  api:
    build:
      dockerfile: dockerfiles/api.dockerfile
    expose:
      - "8000"
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    # volumes:
      # - ./ :/app
    env_file:
      - path: ./.env
    depends_on:
      - redis
      - pgdatabase
    restart: always

  worker:
    container_name: api-celery-worker
    build:
      dockerfile: dockerfiles/api.dockerfile
    command: ./api_worker/celery-entrypoint.sh
    env_file:
      - path: ./.env
    depends_on:
      - api
      - redis
    restart: always

  redis:
    image: redis
  
  pgdatabase:
    image: postgres:13
    env_file:
      - path: ./.env
    ports:
      - 5432:5432
    volumes:
      - database_volume:/var/lib/postgresql/data
    restart: always

volumes:
  database_volume: